### ISSUE TITLE
Generate button still active when edit = false

### ISSUE THREAD

**Issue by Jeffrey-IKUU** [soranoo/strapi-ulid#7]
In the field settings I've disabled editing (Editable field is set to false). When creating a new content type, the field is shown with a valid value. The field is gray instead of white, indicating the editable field is set properly. Still, the generate button is visible and actually creating a new value when clicked. This shouldn't be possible when edit = false.

![image](https://github.com/soranoo/strapi-ulid/assets/77666945/258eb284-e2d1-4def-81dd-63e1c630a43e)

**Comment by Jeffrey-IKUU** [comment]
![Schermafbeelding 2024-03-29 160024](https://github.com/soranoo/strapi-ulid/assets/77666945/9a25068c-2bd0-4df2-b314-0562e7e33e07)

**Comment by Jeffrey-IKUU** [comment]
Just installed 0.1.5 but the button's still there... 

update package, npm install, npm run build but no difference. Also tried to remove node_modules and package-lock and reinstall/rebuild but also without any difference.

**Comment by soranoo** [comment]
Which version of Strapi are you using?

**Comment by Jeffrey-IKUU** [comment]
"dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.2",
    "@strapi/plugin-i18n": "4.5.0",
    "@strapi/plugin-users-permissions": "4.5.0",
    "@strapi/provider-upload-cloudinary": "^4.5.0",
    "@strapi/strapi": "4.11.0",
    "better-sqlite3": "7.4.6",
    "pg": "^8.9.0",
    "strapi-plugin-populate-deep": "^1.1.2",
    "strapi-plugin-website-preview": "^1.0.5",
    "strapi-ulid": "^0.1.5"
  },

**Comment by soranoo** [comment]
A new version `0.1.6` has been released. It should be fine now.

![image](https://github.com/soranoo/strapi-ulid/assets/46896789/b7578397-9654-4b32-863a-38fe0fd66d6a)

**Comment by Jeffrey-IKUU** [comment]
Fixed, thank you!
