### ISSUE TITLE
Broken version 0.1.4 published on npm?

### ISSUE THREAD

**Issue by kodaho** [soranoo/strapi-ulid#8]
At first glance, version 0.1.4 of the package published on npm on March 29th is broken, as it doesn't contain the JavaScript compiled files, located in the `dist/` folder (can be seen by having a look at the package code on npm [here](https://www.npmjs.com/package/strapi-ulid/v/0.1.4?activeTab=code)).

It has been a while since I've done any TypeScript/JavaScript, so don't hesitate if there is something I didn't catch.

**Comment by soranoo** [comment]
Sorry mate, I forgot to build the code. Lets checkout the `0.1.5`~
